# Generated by Django 5.2.18 on 2026-10-07 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
                (
                    "short",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the home page, e.g. 'Grip, stack, thread and pinch'",
                        max_length=120,
                        verbose_name="One-line description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("mint", "Mint"),
                            ("peach", "Peach"),
                            ("sky", "Sky"),
                            ("lilac", "Lilac"),
                            ("sun", "Sunflower"),
                            ("rose", "Rose"),
                        ],
                        default="mint",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="LittleMove", max_length=80)),
                (
                    "tagline",
                    models.CharField(default="Play. Learn. Grow.", max_length=120),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="923173661912",
                        help_text="International format without + or spaces, e.g. 923173661912",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="littlemoveofficial@gmail.com", max_length=254
                    ),
                ),
                ("city", models.CharField(default="Bahawalpur", max_length=60)),
                (
                    "delivery_fee",
                    models.PositiveIntegerField(default=250, help_text="Rs per order"),
                ),
                (
                    "free_delivery_over",
                    models.PositiveIntegerField(
                        default=5000,
                        help_text="Orders at or above this amount (Rs) ship free. 0 = never free.",
                    ),
                ),
                (
                    "cod_enabled",
                    models.BooleanField(default=True, verbose_name="Cash on delivery"),
                ),
                (
                    "jazzcash_number",
                    models.CharField(blank=True, default="03173661912", max_length=20),
                ),
                (
                    "easypaisa_number",
                    models.CharField(blank=True, default="03173661912", max_length=20),
                ),
                (
                    "account_title",
                    models.CharField(blank=True, default="LittleMove", max_length=80),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True,
                        help_text="Bank name, account title and IBAN. Leave empty to hide bank transfer.",
                    ),
                ),
                (
                    "announcement",
                    models.CharField(
                        blank=True,
                        default="Free delivery across Pakistan on orders over Rs 5,000",
                        max_length=140,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Store settings",
                "verbose_name_plural": "Store settings",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=40, verbose_name="SKU"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Selling price in Rs",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional. Shown crossed out if higher than price.",
                        null=True,
                        verbose_name="Old price",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "age_from",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Age from (years)"
                    ),
                ),
                (
                    "age_to",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Age to (years)"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One or two lines for product cards", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "helps_with",
                    models.TextField(
                        blank=True,
                        help_text="One skill per line, e.g. 'Pincer grip'. Shown as a list.",
                    ),
                ),
                (
                    "in_the_box",
                    models.TextField(blank=True, help_text="One item per line."),
                ),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                (
                    "illustration",
                    models.CharField(
                        choices=[
                            ("rings", "Stacking rings"),
                            ("blocks", "Blocks"),
                            ("cards", "Flash cards"),
                            ("balls", "Sensory balls"),
                            ("board", "Balance board"),
                            ("puzzle", "Puzzle"),
                            ("beads", "Threading beads"),
                            ("tunnel", "Tunnel"),
                            ("dough", "Play dough"),
                            ("shapes", "Shape sorter"),
                        ],
                        default="blocks",
                        help_text="Drawing used until you upload a real photo.",
                        max_length=12,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Visible in shop"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Show on home page"
                    ),
                ),
                (
                    "therapist_pick",
                    models.BooleanField(
                        default=False,
                        help_text="Recommended by Wellness Rehabilitation Clinic therapists",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("alt", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
