# Generated by Django 5.2.18 on 2026-10-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Big line, e.g. 'Sensory toys for little explorers'",
                        max_length=80,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=160)),
                ("button_text", models.CharField(default="Shop now", max_length=30)),
                (
                    "link",
                    models.CharField(
                        default="/shop/",
                        help_text="Where the banner goes, e.g. /shop/?sale=1",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Wide picture, 1600×600. With a photo, the text above is shown on top of it.",
                        upload_to="banners/",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional taller version for phones, 800×800.",
                        upload_to="banners/",
                    ),
                ),
                (
                    "image_has_text",
                    models.BooleanField(
                        default=False,
                        help_text="Tick if your picture already contains the text, so we don't print it twice.",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("sky", "Sky blue"),
                            ("mint", "Mint"),
                        ],
                        default="purple",
                        help_text="Background colour when there is no picture",
                        max_length=10,
                    ),
                ),
                (
                    "illustration",
                    models.CharField(
                        choices=[
                            ("rings", "Stacking rings"),
                            ("blocks", "Blocks"),
                            ("cards", "Flash cards"),
                            ("balls", "Sensory balls"),
                            ("board", "Balance board"),
                            ("puzzle", "Puzzle"),
                            ("beads", "Threading beads"),
                            ("tunnel", "Tunnel"),
                            ("dough", "Play dough"),
                            ("shapes", "Shape sorter"),
                        ],
                        default="rings",
                        max_length=12,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional square photo for the category tile (600×600 or bigger).",
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="announcement",
            field=models.CharField(
                blank=True,
                default="Free delivery on orders over Rs 5,000 | Cash on delivery all over Pakistan | Toys chosen with therapists",
                help_text="Top bar messages. Separate several with | and they rotate.",
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. 'Sana, Multan'", max_length=60),
                ),
                ("text", models.TextField(max_length=400)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 stars"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Show on website"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
