# Generated by Django 5.2.18 on 2026-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_banner_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
                (
                    "short",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="One-line description"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("mint", "Mint"),
                            ("peach", "Peach"),
                            ("sky", "Sky"),
                            ("lilac", "Lilac"),
                            ("sun", "Sunflower"),
                            ("rose", "Rose"),
                        ],
                        default="lilac",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="needs",
            field=models.ManyToManyField(
                blank=True,
                help_text="What parents often choose this toy for.",
                related_name="products",
                to="store.need",
            ),
        ),
    ]
