# Generated by Django 5.2.18 on 2026-10-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_need_product_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the chat widget on the website.')),
                ('bot_name', models.CharField(default='Mila', help_text='Name shown in the chat header.', max_length=40)),
                ('welcome_message', models.CharField(default="Hi, I'm Mila! 🌟 I help you find the right toy for your child.\n\nWhat can I help you with?", help_text='First message the bot sends when a visitor opens the chat.', max_length=300)),
                ('quick_reply_1', models.CharField(blank=True, default='🧸 Find a toy', max_length=60)),
                ('quick_reply_2', models.CharField(blank=True, default='🚚 Delivery & shipping', max_length=60)),
                ('quick_reply_3', models.CharField(blank=True, default='💳 Payment methods', max_length=60)),
                ('quick_reply_4', models.CharField(blank=True, default='📦 Track my order', max_length=60)),
                ('quick_reply_5', models.CharField(blank=True, default='💬 Talk to our team', max_length=60)),
                ('quick_reply_6', models.CharField(blank=True, help_text='Optional 6th quick-reply button.', max_length=60)),
                ('fallback_message', models.CharField(default="I'm not sure about that 🤔 Would you like to ask our team on WhatsApp? They reply within minutes.", help_text="Reply sent when the bot can't find an answer.", max_length=300)),
                ('use_ai', models.BooleanField(default=False, help_text='If on and the ANTHROPIC_API_KEY env var is set, the bot will use Claude AI for unknown questions.', verbose_name='Use AI answers (needs ANTHROPIC_API_KEY)')),
            ],
            options={
                'verbose_name': 'Bot settings',
                'verbose_name_plural': 'Bot settings',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('matched', models.BooleanField(default=False, help_text='True if a matching answer was found; False if the bot used the fallback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat log entry',
                'verbose_name_plural': 'Chat history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero_slider', 'Hero slider (banners)'), ('trust_badges', 'Trust badges'), ('shop_by_skill', 'Shop by skill'), ('shop_by_need', 'Shop by need'), ('featured_products', 'Featured products'), ('shop_by_age', 'Shop by age'), ('sale_products', 'Sale products'), ('promo_banners', 'Promo banners'), ('new_arrivals', 'New arrivals'), ('shop_by_budget', 'Shop by budget'), ('therapist_picks', 'Therapist picks'), ('video', 'Video section'), ('gallery', 'Gallery'), ('testimonials', 'What parents say (testimonials)'), ('whatsapp_help', 'WhatsApp help band'), ('faq', 'FAQ / Questions parents ask')], help_text='Each section type can only appear once.', max_length=30, unique=True)),
                ('title', models.CharField(blank=True, help_text='Custom heading — leave blank to use the default.', max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='Untick to hide this section from the home page.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear higher on the page.')),
            ],
            options={
                'verbose_name': 'Home page section',
                'verbose_name_plural': 'Home page sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('image', 'Image (jpg / png / webp)'), ('video', 'Video file (mp4 / webm)'), ('youtube', 'YouTube video')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Image: jpg/png/webp up to 5 MB. Video: mp4/webm up to 50 MB.', upload_to='media_library/')),
                ('youtube_url', models.URLField(blank=True, help_text='Paste the full YouTube video URL.', verbose_name='YouTube URL')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for screen readers.', max_length=200)),
                ('show_in_gallery', models.BooleanField(default=True, help_text='Tick to show this item in the gallery section.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Media item',
                'verbose_name_plural': 'Media library',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label — not shown to visitors.', max_length=80)),
                ('title', models.CharField(help_text='Big heading inside the popup.', max_length=120)),
                ('text', models.TextField(blank=True, help_text='Body text below the heading.')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the popup.', upload_to='popups/')),
                ('button_text', models.CharField(default='Shop now', max_length=40)),
                ('button_link', models.CharField(default='/shop/', help_text='URL the button goes to, e.g. /shop/?sale=1', max_length=200)),
                ('coupon_code', models.CharField(blank=True, help_text='Optional promo code to display (visitors copy it manually).', max_length=40)),
                ('start_at', models.DateTimeField(blank=True, help_text='Leave empty to start showing immediately.', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='Leave empty to show indefinitely.', null=True)),
                ('where', models.CharField(choices=[('all', 'All pages'), ('home', 'Home page only')], default='all', max_length=10)),
                ('delay_seconds', models.PositiveSmallIntegerField(default=3, help_text='Seconds after the page loads before the popup appears.')),
                ('show_again_days', models.PositiveSmallIntegerField(default=7, help_text='After a visitor dismisses it, show again after this many days.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Popup / offer',
                'verbose_name_plural': 'Popups & offers',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='accent_color',
            field=models.CharField(default='#FFC83D', help_text='Highlight colour (hex). Used for stars, badges, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='background_color',
            field=models.CharField(default='#F6F3FF', help_text='Page background colour (hex).', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon, 32×32 or 64×64 px.', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Extra paragraph shown in the website footer.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square logo, 200×200 px or bigger. Shown in admin header.', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(default='#5B3FD6', help_text='Main brand colour (hex, e.g. #5B3FD6). Used for buttons and headings.', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='secondary_color',
            field=models.CharField(default='#FF4F8B', help_text='Secondary brand colour (hex). Used for accents and sale badges.', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description shown in Google search results.', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Browser tab title for the home page. Leave blank to use the store name.', max_length=120),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='share_image',
            field=models.ImageField(blank=True, help_text='Image shown when sharing on WhatsApp / social media. Best size: 1200×630.', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='white_logo',
            field=models.ImageField(blank=True, help_text='White/light version of the logo for dark backgrounds.', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.CreateModel(
            name='BotAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="Main question this answer covers, e.g. 'How do I pay?'", max_length=200)),
                ('keywords', models.TextField(help_text='Words or phrases that trigger this answer, one per line.\nInclude key words from the question itself, e.g.:\npayment\ncod\ncash\npay\nhow to pay')),
                ('answer', models.TextField(help_text='The reply the bot will send.')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional: link to a category mentioned in the answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.category')),
                ('product', models.ForeignKey(blank=True, help_text='Optional: link to a product mentioned in the answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product')),
            ],
            options={
                'verbose_name': 'Bot answer',
                'verbose_name_plural': 'Questions & answers',
                'ordering': ['question'],
            },
        ),
    ]
