# Generated by Django 5.2.18 on 2026-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_section_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='type',
            field=models.CharField(choices=[('hero_slider', 'Hero slider (banners)'), ('trust_badges', 'Trust badges'), ('shop_by_skill', 'Shop by skill'), ('shop_by_need', 'Shop by need'), ('featured_products', 'Featured products'), ('shop_by_age', 'Shop by age'), ('sale_products', 'Sale products'), ('promo_banners', 'Promo banners'), ('new_arrivals', 'New arrivals'), ('shop_by_budget', 'Shop by budget'), ('therapist_picks', 'Therapist picks'), ('video', 'Video section'), ('gallery', 'Gallery'), ('testimonials', 'What parents say (testimonials)'), ('whatsapp_help', 'WhatsApp help band'), ('faq', 'FAQ / Questions parents ask'), ('save_with_bundles', 'Save with bundles'), ('our_story', 'Our story'), ('why_us', 'Why parents choose LittleMove'), ('final_cta', 'Final CTA (Ready to find their favourite?)')], help_text='Each section type can only appear once.', max_length=30, unique=True),
        ),
    ]
