# Generated by Django 5.2.18 on 2026-10-10 06:29

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0013_default_quick_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Branding & logo',
                'verbose_name_plural': 'Branding & logo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.storesettings',),
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery settings',
                'verbose_name_plural': 'Delivery settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.storesettings',),
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Payment settings',
                'verbose_name_plural': 'Payment settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.storesettings',),
        ),
        migrations.CreateModel(
            name='RoleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Staff user',
                'verbose_name_plural': 'Staff users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Store info',
                'verbose_name_plural': 'Store info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.storesettings',),
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Default roles are reset by setup_roles on every deploy.')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role profile',
                'verbose_name_plural': 'Role profiles',
            },
        ),
    ]
