# Generated by Django 5.2.18 on 2026-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_roles_and_proxy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_ur',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Subtitle (Urdu)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ur',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Urdu)'),
        ),
        migrations.AddField(
            model_name='botanswer',
            name='answer_ur',
            field=models.TextField(blank=True, default='', verbose_name='Answer (Urdu)'),
        ),
        migrations.AddField(
            model_name='botanswer',
            name='question_ur',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Question keywords (Urdu)'),
        ),
        migrations.AddField(
            model_name='botanswer',
            name='quick_label_ur',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Quick button label (Urdu)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='Description (Urdu)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ur',
            field=models.TextField(blank=True, default='', verbose_name='Answer (Urdu)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ur',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Question (Urdu)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle_ur',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Subtitle (Urdu)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='title_ur',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Urdu)'),
        ),
        migrations.AddField(
            model_name='need',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='Description (Urdu)'),
        ),
        migrations.AddField(
            model_name='need',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ur',
            field=models.TextField(blank=True, default='', verbose_name='Description (Urdu)'),
        ),
        migrations.AddField(
            model_name='product',
            name='helps_with_ur',
            field=models.TextField(blank=True, default='', verbose_name='Helps with (Urdu)'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_the_box_ur',
            field=models.TextField(blank=True, default='', verbose_name='In the box (Urdu)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Urdu)'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_ur',
            field=models.TextField(blank=True, default='', verbose_name='Summary (Urdu)'),
        ),
    ]
