# Generated by Django 5.2.18 on 2026-10-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_banner_subtitle_ur_banner_title_ur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='need',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Need', 'verbose_name_plural': 'Needs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
