"""
Languages for the LittleMove language dropdown.
GT_LANGUAGES = languages powered by Google Website Translator.
"""

# Google Translate language codes + display info
# code = Google Translate combo value (NOT BCP47 — note iw=Hebrew, zh-CN/zh-TW, etc.)
GT_LANGUAGES = [
    # (gt_code, native_name, english_name, is_rtl)
    ("af",    "Afrikaans",            "Afrikaans",         False),
    ("sq",    "Shqip",                "Albanian",          False),
    ("am",    "አማርኛ",                 "Amharic",           False),
    ("ar",    "العربية",              "Arabic",            True),
    ("hy",    "Հայերեն",              "Armenian",          False),
    ("az",    "Azərbaycan",           "Azerbaijani",       False),
    ("eu",    "Euskara",              "Basque",            False),
    ("be",    "Беларуская",           "Belarusian",        False),
    ("bn",    "বাংলা",                "Bangla",            False),
    ("bs",    "Bosanski",             "Bosnian",           False),
    ("bg",    "Български",            "Bulgarian",         False),
    ("ca",    "Català",               "Catalan",           False),
    ("ceb",   "Cebuano",              "Cebuano",           False),
    ("zh-CN", "中文（简体）",            "Chinese (Simplified)", False),
    ("zh-TW", "中文（繁體）",            "Chinese (Traditional)", False),
    ("co",    "Corsu",                "Corsican",          False),
    ("hr",    "Hrvatski",             "Croatian",          False),
    ("cs",    "Čeština",              "Czech",             False),
    ("da",    "Dansk",                "Danish",            False),
    ("nl",    "Nederlands",           "Dutch",             False),
    ("eo",    "Esperanto",            "Esperanto",         False),
    ("et",    "Eesti",                "Estonian",          False),
    ("fi",    "Suomi",                "Finnish",           False),
    ("fr",    "Français",             "French",            False),
    ("fy",    "Frysk",                "Frisian",           False),
    ("gl",    "Galego",               "Galician",          False),
    ("ka",    "ქართული",              "Georgian",          False),
    ("de",    "Deutsch",              "German",            False),
    ("el",    "Ελληνικά",             "Greek",             False),
    ("gu",    "ગુજરાતી",               "Gujarati",          False),
    ("ht",    "Kreyòl ayisyen",       "Haitian Creole",    False),
    ("ha",    "Hausa",                "Hausa",             False),
    ("haw",   "ʻŌlelo Hawaiʻi",       "Hawaiian",          False),
    ("iw",    "עברית",                "Hebrew",            True),
    ("hi",    "हिन्दी",               "Hindi",             False),
    ("hmn",   "Hmong",                "Hmong",             False),
    ("hu",    "Magyar",               "Hungarian",         False),
    ("is",    "Íslenska",             "Icelandic",         False),
    ("ig",    "Igbo",                 "Igbo",              False),
    ("id",    "Bahasa Indonesia",     "Indonesian",        False),
    ("ga",    "Gaeilge",              "Irish",             False),
    ("it",    "Italiano",             "Italian",           False),
    ("ja",    "日本語",                "Japanese",          False),
    ("jw",    "Basa Jawa",            "Javanese",          False),
    ("kn",    "ಕನ್ನಡ",                "Kannada",           False),
    ("kk",    "Қазақ",                "Kazakh",            False),
    ("km",    "ខ្មែរ",                "Khmer",             False),
    ("rw",    "Kinyarwanda",          "Kinyarwanda",       False),
    ("ko",    "한국어",                "Korean",            False),
    ("ku",    "Kurdî",                "Kurdish (Kurmanji)",False),
    ("ky",    "Кыргызча",             "Kyrgyz",            False),
    ("lo",    "ລາວ",                  "Lao",               False),
    ("la",    "Latina",               "Latin",             False),
    ("lv",    "Latviešu",             "Latvian",           False),
    ("lt",    "Lietuvių",             "Lithuanian",        False),
    ("lb",    "Lëtzebuergesch",       "Luxembourgish",     False),
    ("mk",    "Македонски",           "Macedonian",        False),
    ("mg",    "Malagasy",             "Malagasy",          False),
    ("ms",    "Bahasa Melayu",        "Malay",             False),
    ("ml",    "മലയാളം",               "Malayalam",         False),
    ("mt",    "Malti",                "Maltese",           False),
    ("mi",    "Te Reo Māori",         "Maori",             False),
    ("mr",    "मराठी",                "Marathi",           False),
    ("mn",    "Монгол",               "Mongolian",         False),
    ("my",    "မြန်မာ",               "Myanmar (Burmese)", False),
    ("ne",    "नेपाली",               "Nepali",            False),
    ("no",    "Norsk",                "Norwegian",         False),
    ("ny",    "Chichewa",             "Nyanja (Chichewa)", False),
    ("or",    "ଓଡ଼ିଆ",                "Odia (Oriya)",      False),
    ("ps",    "پښتو",                 "Pashto",            True),
    ("fa",    "فارسی",                "Persian",           True),
    ("pl",    "Polski",               "Polish",            False),
    ("pt",    "Português",            "Portuguese",        False),
    ("pa",    "ਪੰਜਾਬੀ",               "Punjabi",           False),
    ("ro",    "Română",               "Romanian",          False),
    ("ru",    "Русский",              "Russian",           False),
    ("sm",    "Samoan",               "Samoan",            False),
    ("gd",    "Gàidhlig",             "Scots Gaelic",      False),
    ("sr",    "Српски",               "Serbian",           False),
    ("st",    "Sesotho",              "Sesotho",           False),
    ("sn",    "Shona",                "Shona",             False),
    ("sd",    "سنڌي",                 "Sindhi",            True),
    ("si",    "සිංහල",                "Sinhala",           False),
    ("sk",    "Slovenčina",           "Slovak",            False),
    ("sl",    "Slovenščina",          "Slovenian",         False),
    ("so",    "Soomaali",             "Somali",            False),
    ("es",    "Español",              "Spanish",           False),
    ("su",    "Basa Sunda",           "Sundanese",         False),
    ("sw",    "Kiswahili",            "Swahili",           False),
    ("sv",    "Svenska",              "Swedish",           False),
    ("tl",    "Filipino",             "Tagalog (Filipino)",False),
    ("tg",    "Тоҷикӣ",               "Tajik",             False),
    ("ta",    "தமிழ்",                "Tamil",             False),
    ("tt",    "Татарча",              "Tatar",             False),
    ("te",    "తెలుగు",               "Telugu",            False),
    ("th",    "ภาษาไทย",              "Thai",              False),
    ("tr",    "Türkçe",               "Turkish",           False),
    ("tk",    "Türkmen",              "Turkmen",           False),
    ("uk",    "Українська",           "Ukrainian",         False),
    ("ug",    "ئۇيغۇرچە",             "Uyghur",            True),
    ("ur",    "اردو",                 "Urdu",              True),
    ("uz",    "O'zbek",               "Uzbek",             False),
    ("vi",    "Tiếng Việt",           "Vietnamese",        False),
    ("cy",    "Cymraeg",              "Welsh",             False),
    ("xh",    "isiXhosa",             "Xhosa",             False),
    ("yi",    "ייִדיש",               "Yiddish",           True),
    ("yo",    "Yorùbá",               "Yoruba",            False),
    ("zu",    "isiZulu",              "Zulu",              False),
]

# Codes of RTL languages (for Google-translated languages)
GT_RTL_CODES = {lang[0] for lang in GT_LANGUAGES if lang[3]}
