# Generated by Django 5.2.18 on 2026-10-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "New — needs confirming"),
                            ("confirmed", "Confirmed"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(max_length=60)),
                ("address", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on delivery"),
                            ("jazzcash", "JazzCash"),
                            ("easypaisa", "EasyPaisa"),
                            ("bank", "Bank transfer"),
                        ],
                        default="cod",
                        max_length=12,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("checking", "Customer says paid — check"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Transaction ID"
                    ),
                ),
                ("subtotal", models.PositiveIntegerField()),
                ("delivery_fee", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "courier",
                    models.CharField(
                        blank=True, help_text="e.g. TCS, Leopards, M&P", max_length=60
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=60)),
                (
                    "internal_note",
                    models.TextField(blank=True, help_text="Only visible in admin"),
                ),
                ("stock_restored", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(blank=True, max_length=40)),
                ("price", models.PositiveIntegerField()),
                ("qty", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
