# Generated by Django 5.2.18 on 2026-10-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'New – needs confirming'), ('confirmed', 'Confirmed'), ('packed', 'Packed – ready for pickup'), ('shipped', 'Picked up – on the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('on_hold', 'On hold'), ('returned', 'Returned')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Status change'), ('payment', 'Payment change'), ('note', 'Note added')], max_length=10)),
                ('from_value', models.CharField(blank=True, max_length=40)),
                ('to_value', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
